$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://raw.githubusercontent.com/FlatFilers/flatfile-docs-kitchen-sink/main/typescript/fetch-schemas/example-schemas/yaml/product.yml"
title: "Product"
description: "A product from Acme's catalog"
type: "object"
properties:
  productId:
    description: "The unique identifier for a product"
    type: "integer"

  productName:
    description: "Name of the product"
    type: "string"

  price:
    description: "The price of the product"
    type: "number"
    exclusiveMinimum: 0

  tags:
    description: "Tags for the product"
    type: "array"
    items:
      type: "string"

    minItems: 1
    uniqueItems: true

  dimensions:
    type: "object"
    properties:
      length:
        type: "number"

      width:
        type: "number"

      height:
        type: "number"

    required: ["length", "width", "height"]

required: ["productId", "productName", "price"]
